### ISSUE TITLE
Webpage for note, warning and url tag not found

### ISSUE THREAD

**Issue by Bi0T1N** [pasdoc/pasdoc.github.io#1]
The webpages for the note, warning and url tags are not available and thus resulting in 404:

> https://pasdoc.github.io/NoteAndWarningTags
> https://pasdoc.github.io/UrlTag

The wiki on [pasdoc](/pasdoc/pasdoc/wiki) lists them:

> https://github.com/pasdoc/pasdoc/wiki/NoteAndWarningTags
> https://github.com/pasdoc/pasdoc/wiki/UrlTag

Maybe the `synchronize_from_wiki.sh` should do `git pull` :smile:

**Comment by michaliskambi** [comment]
Thanks fixed! These 2 pages used default Markdown format, while `synchronize_from_wiki` assumed that everything is in AsciiDoctor format.

For now I'd prefer to keep `git pull` outside of `synchronize_from_wiki`, this way it  works offline and one can be sure that executing it multiple times should make no change to the output.

**Comment by Bi0T1N** [comment]
Ah okay, didn't cloned the wiki git - just assumed you worked with an older version. However, thanks for the fast fix :)
